### ISSUE TITLE
Validate Energy demand

### ISSUE THREAD

**Issue by raphyphy** [OmdenaAI/omdena-philippines-renewable#24]
**Is your feature request related to a problem? Please describe.**

- After computing the estimated energy demand per municipality, we compute the accuracy of the methodology used using DHS dataset

**Describe the solution you'd like**

Solution # 1

- [x] Download the nightlight settlement zonal stats (from #20 ) **[x1]**
- [x] Download the geocoded DHS (from #12) **[x2]**
- [x] Parse the **mean** column from **x1** as the estimated energy demand
- [x] Compute the error between the **lit_per** from **x1** and **Has Electricity** from **x2**
- [x] Create a notebook compiling the solution

Solution # 2

- [ ] Download the nightlight settlement zonal stats (from #20 ) **[x1]**
- [ ] Download the geocoded DHS (from #12) **[x2]**
- [ ] Download the DOE power grid dataset **[x3]**
- [ ] Create a function **f(x1,x2,x3)** that scans for (1) presence of settlement, (2) NTL intensity (3) absence of power grid source within 5-10km for each municipality. **[y]**
- [ ] Compute the error between **y** and **Has Electricity** from **x2**
- [ ] Create a notebook compiling the solution

**Describe alternatives you've considered**

- n/a

**Additional context**

- Dependent on #16
